// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOben78eWwjSttIrKL9QU8jXK3FzbDfls',
    appId: '1:1004013521573:web:38ef5e6fd1fa45ea599b4c',
    messagingSenderId: '1004013521573',
    projectId: 'keyinside',
    authDomain: 'keyinside.firebaseapp.com',
    storageBucket: 'keyinside.firebasestorage.app',
    measurementId: 'G-RKL72FXK0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFhFtA2-IzAXBzyydrwrBuUaVa0_DMfPQ',
    appId: '1:1004013521573:android:b270092fc8d07c20599b4c',
    messagingSenderId: '1004013521573',
    projectId: 'keyinside',
    storageBucket: 'keyinside.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv33KLhqoedb-3ZP8AQ8EnOOdRYxV9OGE',
    appId: '1:1004013521573:ios:5677a0336263cec9599b4c',
    messagingSenderId: '1004013521573',
    projectId: 'keyinside',
    storageBucket: 'keyinside.firebasestorage.app',
    iosBundleId: 'com.example.projectAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv33KLhqoedb-3ZP8AQ8EnOOdRYxV9OGE',
    appId: '1:1004013521573:ios:5677a0336263cec9599b4c',
    messagingSenderId: '1004013521573',
    projectId: 'keyinside',
    storageBucket: 'keyinside.firebasestorage.app',
    iosBundleId: 'com.example.projectAndroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOben78eWwjSttIrKL9QU8jXK3FzbDfls',
    appId: '1:1004013521573:web:0890e0316c7723be599b4c',
    messagingSenderId: '1004013521573',
    projectId: 'keyinside',
    authDomain: 'keyinside.firebaseapp.com',
    storageBucket: 'keyinside.firebasestorage.app',
    measurementId: 'G-J45Q4XSCGM',
  );
}
